rails6-bookers2-debug-ruby3-main/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users

  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments,only: [:create]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/search', to: 'searches#search'
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails6-bookers2-debug-ruby3-main/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

rails6-bookers2-debug-ruby3-main/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
  end

end

rails6-bookers2-debug-ruby3-main/app/helpers/favorites_helper.rb
module FavoritesHelper
end

rails6-bookers2-debug-ruby3-main/app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
 <%= link_to book_favorites_path(book),method: :delete, local: false do %>
  <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
  <%= book.favorites.count %>
 <% end %>
<% else %>
 <%= link_to book_favorites_path(book), method: :post, local: false do %>
  <i class="fas fa-heart" aria-hidden="true"></i>
  <%= book.favorites.count %>
 <% end %>
<% end %>

rails6-bookers2-debug-ruby3-main/app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

rails6-bookers2-debug-ruby3-main/app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");